/**
 * Email Testing Script
 * 
 * This script tests the email configuration and sends a test email
 * to verify SMTP settings are working correctly.
 */

require('dotenv').config();
const { sendSystemEmail, verifyEmailConfig } = require('../services/emailService');

async function testEmailConfiguration() {
  console.log('🧪 [EMAIL TEST] Starting email configuration test...\n');
  
  // Test 1: Validate configuration
  console.log('📋 [EMAIL TEST] Step 1: Validating email configuration...');
  const { validateEmailConfig } = require('../services/emailService');
  const configValid = validateEmailConfig();
  
  if (!configValid) {
    console.error('❌ [EMAIL TEST] Email configuration is invalid. Please check your environment variables.');
    return;
  }
  
  // Test 2: Test SMTP connection
  console.log('\n📋 [EMAIL TEST] Step 2: Testing SMTP connection...');
  const connectionResult = await verifyEmailConfig();
  
  if (!connectionResult.success) {
    console.error('❌ [EMAIL TEST] SMTP connection failed:', connectionResult.error);
    console.error('❌ [EMAIL TEST] Error details:', connectionResult.details);
    return;
  }
  
  // Test 3: Send test email
  console.log('\n📋 [EMAIL TEST] Step 3: Sending test email...');
  
  const testEmail = process.argv[2]; // Get email from command line argument
  
  if (!testEmail) {
    console.error('❌ [EMAIL TEST] Please provide a test email address as an argument');
    console.log('Usage: node scripts/testEmail.js your-email@example.com');
    return;
  }
  
  console.log('📧 [EMAIL TEST] Sending test email to:', testEmail);
  
  const subject = 'Test Email - MBZ Technology Platform';
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Test Email</title>
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: #007bff; color: white; padding: 20px; text-align: center; }
        .content { padding: 20px; background: #f8f9fa; }
        .success { background: #d4edda; border: 1px solid #c3e6cb; padding: 15px; margin: 15px 0; border-radius: 5px; color: #155724; }
        .footer { text-align: center; padding: 20px; color: #666; font-size: 12px; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>🧪 Test Email</h1>
        </div>
        
        <div class="content">
          <h2>Hello!</h2>
          <p>This is a test email from the MBZ Technology Platform to verify that email sending is working correctly.</p>
          
          <div class="success">
            <strong>✅ Email Configuration Test Successful!</strong>
            <p>If you're receiving this email, it means:</p>
            <ul>
              <li>SMTP configuration is correct</li>
              <li>Authentication is working</li>
              <li>Email sending is functional</li>
            </ul>
          </div>
          
          <p><strong>Test Details:</strong></p>
          <ul>
            <li><strong>Sent at:</strong> ${new Date().toLocaleString()}</li>
            <li><strong>From:</strong> ${process.env.SMTP_FROM || process.env.SMTP_USER}</li>
            <li><strong>SMTP Host:</strong> ${process.env.SMTP_HOST || 'mbztechnology.com'}</li>
            <li><strong>SMTP Port:</strong> ${process.env.SMTP_PORT || '465'}</li>
          </ul>
          
          <p>This test email was generated by the email testing script.</p>
        </div>
        
        <div class="footer">
          <p>This is a test email from MBZ Technology Platform</p>
          <p>© ${new Date().getFullYear()} MBZ Technology. All rights reserved.</p>
        </div>
      </div>
    </body>
    </html>
  `;
  
  const textContent = `
    Test Email - MBZ Technology Platform
    
    Hello!
    
    This is a test email from the MBZ Technology Platform to verify that email sending is working correctly.
    
    ✅ Email Configuration Test Successful!
    
    If you're receiving this email, it means:
    - SMTP configuration is correct
    - Authentication is working
    - Email sending is functional
    
    Test Details:
    - Sent at: ${new Date().toLocaleString()}
    - From: ${process.env.SMTP_FROM || process.env.SMTP_USER}
    - SMTP Host: ${process.env.SMTP_HOST || 'mbztechnology.com'}
    - SMTP Port: ${process.env.SMTP_PORT || '465'}
    
    This test email was generated by the email testing script.
    
    ---
    This is a test email from MBZ Technology Platform
    © ${new Date().getFullYear()} MBZ Technology. All rights reserved.
  `;
  
  try {
    const emailResult = await sendSystemEmail(testEmail, subject, htmlContent, textContent);
    
    if (emailResult.success) {
      console.log('✅ [EMAIL TEST] Test email sent successfully!');
      console.log('✅ [EMAIL TEST] Message ID:', emailResult.messageId);
      console.log('✅ [EMAIL TEST] Response:', emailResult.response);
      console.log('✅ [EMAIL TEST] Accepted:', emailResult.accepted);
      if (emailResult.rejected && emailResult.rejected.length > 0) {
        console.log('❌ [EMAIL TEST] Rejected:', emailResult.rejected);
      }
    } else {
      console.error('❌ [EMAIL TEST] Failed to send test email:', emailResult.error);
      console.error('❌ [EMAIL TEST] Error details:', emailResult.details);
    }
  } catch (error) {
    console.error('❌ [EMAIL TEST] Error sending test email:', error);
  }
  
  console.log('\n🧪 [EMAIL TEST] Email configuration test completed!');
}

// Run the test
testEmailConfiguration().catch(console.error);
